export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"

export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const AUTH_USER = "AUTH_USER"

export const CLEAN_ALERTS = "CLEAN_ALERTS"